config/routes.rb
Rails.application.routes.draw do
  resources :shots
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "shots#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shots, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: %i[ show edit update destroy ]

  # GET /shots or /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1 or /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = Shot.new
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots or /shots.json
  def create
    @shot = Shot.new(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to shot_url(@shot), notice: "Shot was successfully created." }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1 or /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to shot_url(@shot), notice: "Shot was successfully updated." }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1 or /shots/1.json
  def destroy
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to shots_url, notice: "Shot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/home/index.html.erb
<br>
<h1>hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DribbbleClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5 has-text-white">Dribbble Clone</h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div id="navbar" class="navbar-menu">
          <div class="navbar-start">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'Shots', root_path , class:"button is-dark" %>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div id="navbar" class="navbar-menu">
          <div class="navbar-start">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'Shots', root_path , class:"button is-dark" %>
                </p>
              </div>
            </div>
          </div>
        </nav>
        <div class="container"><%= yield %></div>
      </body>
    </html>

app/views/shots/_form.html.erb
<%= simple_form_for(@shot) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shots/_shot.html.erb
<div id="<%= dom_id shot %>">
  <p>
    <strong>Title:</strong>
    <%= shot.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= shot.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= shot.user_id %>
  </p>

</div>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Show this shot", @shot %> |
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/index.html.erb
<br>
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-size-5">
        What are you working on? <span class="has-text-grey-light">Dribbble is where designers get inspired and hired.</span>
      </h1>
      <div class="content">
        <%= link_to "Login", new_user_session_path, class: "button is-primary" %>
      </div>
    </div>
  </div>
</section>

app/views/shots/new.html.erb
<h1>New shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shot %>

<div>
  <%= link_to "Edit this shot", edit_shot_path(@shot) %> |
  <%= link_to "Back to shots", shots_path %>

  <%= button_to "Destroy this shot", @shot, method: :delete %>
</div>